import img1 from "@assets/girl.jpg";
import img2 from "@assets/Strength Coach.jpg";
import img3 from "@assets/legGroup.webp";
import img4 from "@assets/user.webp";
import img5 from "@assets/registerTrainer.webp";
import img6 from "@assets/RegisterCoach (1).jpg";
import img7 from "@assets/review2.jpeg";
import actionPhoto1 from "@assets/ActionPhoto1.avif";
import actionPhoto2 from "@assets/actionPhoto2.jpg";
import actionPhoto3 from "@assets/actionPhoto3.jpg";
import actionPhoto4 from "@assets/actionPhoto4.webp";
import actionPhoto5 from "@assets/actionPhoto5.jpg";
export const sampleCoaches = [
  {
    id: 0,
    name: "John Doe",
    category: "Fitness Coach",
    categories: ["Football", "Fitness", "Swimming", "Basketball"],
    rating: 3,
    reviews: 90,
    badge: "Gold",
    trainingOffer: true,
    verified: true,
    summary:
      "Professional trainer, experience with athletes ranging from pro to youth. As a former pro athlete, I understand what it takes to reach your fitness goals. Sports Science degree",
    location: "LA",
    distance: 6.5,
    salary: 22,
    image: img1,
    recommended: true,
    trainingType: "In-Person",
    gender: "Male",
    responseRate: 100,
    packages: [
      {
        id: 1,
        packageType: "Light",
        trainingType: "in-person",
        recommended: false,
        title: "In-Person Training for up to 4 athletes",
        description: `3 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 105,
        sessionSalary: "3 sessions ($35/ea)",
      },
      {
        id: 2,
        packageType: "Standard",
        trainingType: "in-person",
        recommended: true,
        title: "In-Person Training for up to 10 athletes",
        description: `6 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 175,
        sessionSalary: "6 sessions ($35/ea)",
      },
      {
        id: 3,
        packageType: "Pro",
        trainingType: "online",
        recommended: false,
        title: "Online Training for a single athlete",
        description: `10 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 250,
        sessionSalary: "10 sessions ($35/ea)",
      },
    ],
    credentials: [
      {
        id: 1,
        college: ["x EssexxCounty", "Community College (NJ)"],
        experience: "30 years",
        accreditations: [
          "x EssexxCounty Qualified",
          "Private Coach",
          "Passed Coach Course",
        ],
      },
    ],
    services: [
      {
        ages: ["Kids", "Teenagers"],
        positions: [
          "Offensive Line",
          "Defensive Back",
          "Kicker",
          "Quarterback",
          "Running Back",
          "Tight End",
          "Wide Receiver",
          "Defensive Line",
          "Linebacker",
        ],
        specialties: [
          "Blocking",
          "Catching",
          "Jamming",
          "Kicking",
          "Special Teams",
          "Tackling",
          "Throwing",
          "Pass Defense",
          "Footwork",
          "Route Running",
          "Hand Placement",
        ],
      },
    ],
    actionPhotos: [
      actionPhoto1,
      actionPhoto2,
      actionPhoto3,
      actionPhoto4,
      actionPhoto5,
    ],
    experience:
      "I have played sports like baseball, football, basketball and boxing. I have played football from age 8 up to age 18, were I learned to play both side of the ball. I have played youth and semi pro football. I have been coaching football on two levels one as a semi pro and the other as a youth coach. I started coaching semi pro in 1994 up until 2007. and I started coaching youth football in 1996. at both levels I coach defense , I attend Glazer football Clinic an I'm USA coach certified. I still coach youth football now for the Linden Tigers. I also coach baseball for the linden PAL , which I have been doing for 3years now. Before than II coached in East Orange Little League two years, and Newark Little League for 3 years. I now have my own double A adult baseball team which has play in 3 se",
    highlights:
      "Won 5 championship and 6 division championship these are with both semi pro and youth football. I have some of my players go on to play in the NFL and a few other play arena football.l I have taught players skill and technique to help them develop in this sport they play.. I also know Baseball, basketball, and boxing as well.",
    plan: "First I will talk to my client to see where he/ she is having problem or need up. After that I will have him or her warm up than we will go through some drill. than we will work on the problem, Than we will put everything together.exploding out of your stand to receive the ball . Than we will work on the receiving the ball from the quarterback. Learn the holes and the different way offensive use them. You will learn how to come out of the back field, running your ro out of the back field.utes to catch a pass.",
  },
  {
    id: 1,
    name: "leo",
    category: "Fitness Coach",
    categories: ["Football", "Fitness", "Swimming", "Basketball"],
    rating: 4,
    reviews: 100,
    badge: "silver",
    trainingOffer: true,
    verified: true,
    summary:
      "Professional trainer, experience with athletes ranging from pro to youth. As a former pro athlete, I understand what it takes to reach your fitness goals. Sports Science degree",
    location: "LA",
    distance: 5.5,
    verified: true,
    salary: 80,
    image: img2,
    recommended: true,
    trainingType: "Online",
    gender: "Male",
    responseRate: 100,
    packages: [
      {
        id: 1,
        packageType: "Light",
        trainingType: "in-person",
        recommended: false,
        title: "In-Person Training for up to 4 athletes",
        description: `3 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 105,
        sessionSalary: "3 sessions ($35/ea)",
      },
      {
        id: 2,
        packageType: "Standard",
        trainingType: "in-person",
        recommended: true,
        title: "In-Person Training for up to 10 athletes",
        description: `6 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 175,
        sessionSalary: "6 sessions ($35/ea)",
      },
      {
        id: 3,
        packageType: "Pro",
        trainingType: "online",
        recommended: false,
        title: "Online Training for a single athlete",
        description: `10 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 250,
        sessionSalary: "10 sessions ($35/ea)",
      },
    ],
    credentials: [
      {
        id: 2,
        college: ["x EssexxCounty", "Community College (NJ)"],
        experience: "30 years",
        accreditations: [
          "x EssexxCounty Qualified",
          "Private Coach",
          "Passed Coach Course",
        ],
      },
    ],
    services: [
      {
        ages: ["Kids", "Teenagers"],
        positions: [
          "Offensive Line",
          "Defensive Back",
          "Kicker",
          "Quarterback",
          "Running Back",
          "Tight End",
          "Wide Receiver",
          "Defensive Line",
          "Linebacker",
        ],
        specialties: [
          "Blocking",
          "Catching",
          "Jamming",
          "Kicking",
          "Special Teams",
          "Tackling",
          "Throwing",
          "Pass Defense",
          "Footwork",
          "Route Running",
          "Hand Placement",
        ],
      },
    ],
    actionPhotos: [
      actionPhoto1,
      actionPhoto2,
      actionPhoto3,
      actionPhoto4,
      actionPhoto5,
    ],
    experience:
      "I have played sports like baseball, football, basketball and boxing. I have played football from age 8 up to age 18, were I learned to play both side of the ball. I have played youth and semi pro football. I have been coaching football on two levels one as a semi pro and the other as a youth coach. I started coaching semi pro in 1994 up until 2007. and I started coaching youth football in 1996. at both levels I coach defense , I attend Glazer football Clinic an I'm USA coach certified. I still coach youth football now for the Linden Tigers. I also coach baseball for the linden PAL , which I have been doing for 3years now. Before than II coached in East Orange Little League two years, and Newark Little League for 3 years. I now have my own double A adult baseball team which has play in 3 se",
    highlights:
      "Won 5 championship and 6 division championship these are with both semi pro and youth football. I have some of my players go on to play in the NFL and a few other play arena football.l I have taught players skill and technique to help them develop in this sport they play.. I also know Baseball, basketball, and boxing as well.",
    plan: "First I will talk to my client to see where he/ she is having problem or need up. After that I will have him or her warm up than we will go through some drill. than we will work on the problem, Than we will put everything together.exploding out of your stand to receive the ball . Than we will work on the receiving the ball from the quarterback. Learn the holes and the different way offensive use them. You will learn how to come out of the back field, running your ro out of the back field.utes to catch a pass.",
  },
  {
    id: 2,
    name: "leo",
    category: "Fitness Coach",
    categories: ["Football", "Fitness", "Swimming", "Basketball"],
    rating: 4,
    reviews: 100,
    badge: "silver",
    trainingOffer: true,
    summary:
      "Professional trainer, experience with athletes ranging from pro to youth. As a former pro athlete, I understand what it takes to reach your fitness goals. Sports Science degree",
    location: "LA",
    distance: 5.5,
    verified: true,
    salary: 110,
    image: img3,
    recommended: false,
    trainingType: "Online",
    gender: "Male",
    responseRate: 100,
    packages: [
      {
        id: 1,
        packageType: "Light",
        trainingType: "in-person",
        title: "In-Person Training for up to 4 athletes",
        recommended: false,
        description: `3 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 105,
        sessionSalary: "3 sessions ($35/ea)",
      },
      {
        id: 2,
        packageType: "Standard",
        trainingType: "in-person",
        title: "In-Person Training for up to 10 athletes",
        recommended: true,
        description: `6 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 175,
        sessionSalary: "6 sessions ($35/ck, Quaea)",
      },
      {
        id: 3,
        packageType: "Pro",
        trainingType: "online",
        recommended: false,
        title: "Online Training for a single athlete",
        description: `10 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 250,
        sessionSalary: "10 sessions ($35/ea)",
      },
    ],
    credentials: [
      {
        id: 3,
        college: ["x EssexxCounty", "Community College (NJ)"],
        experience: "30 years",
        accreditations: [
          "x EssexxCounty Qualified",
          "Private Coach",
          "Passed Coach Course",
        ],
      },
    ],
    services: [
      {
        ages: ["Kids", "Teenagers"],
        positions: [
          "Offensive Line",
          "Defensive Back",
          "Kicker",
          "Quarterback",
          "Running Back",
          "Tight End",
          "Wide Receiver",
          "Defensive Line",
          "Linebacker",
        ],
        specialties: [
          "Blocking",
          "Catching",
          "Jamming",
          "Kicking",
          "Special Teams",
          "Tackling",
          "Throwing",
          "Pass Defense",
          "Footwork",
          "Route Running",
          "Hand Placement",
        ],
      },
    ],
    actionPhotos: [
      actionPhoto1,
      actionPhoto2,
      actionPhoto3,
      actionPhoto4,
      actionPhoto5,
    ],
    experience:
      "I have played sports like baseball, football, basketball and boxing. I have played football from age 8 up to age 18, were I learned to play both side of the ball. I have played youth and semi pro football. I have been coaching football on two levels one as a semi pro and the other as a youth coach. I started coaching semi pro in 1994 up until 2007. and I started coaching youth football in 1996. at both levels I coach defense , I attend Glazer football Clinic an I'm USA coach certified. I still coach youth football now for the Linden Tigers. I also coach baseball for the linden PAL , which I have been doing for 3years now. Before than II coached in East Orange Little League two years, and Newark Little League for 3 years. I now have my own double A adult baseball team which has play in 3 se",
    highlights:
      "Won 5 championship and 6 division championship these are with both semi pro and youth football. I have some of my players go on to play in the NFL and a few other play arena football.l I have taught players skill and technique to help them develop in this sport they play.. I also know Baseball, basketball, and boxing as well.",
    plan: "First I will talk to my client to see where he/ she is having problem or need up. After that I will have him or her warm up than we will go through some drill. than we will work on the problem, Than we will put everything together.exploding out of your stand to receive the ball . Than we will work on the receiving the ball from the quarterback. Learn the holes and the different way offensive use them. You will learn how to come out of the back field, running your ro out of the back field.utes to catch a pass.",
  },
  {
    id: 3,
    name: "leo",
    category: "Fitness Coach",
    categories: ["Football", "Fitness", "Swimming", "Basketball"],
    rating: 4,
    reviews: 100,
    badge: "silver",
    summary:
      "Professional trainer, experience with athletes ranging from pro to youth. As a former pro athlete, I understand what it takes to reach your fitness goals. Sports Science degree",
    location: "LA",
    distance: 5.5,
    verified: true,
    salary: 60,
    image: img4,
    recommended: true,
    trainingType: "Online",
    gender: "Male",
    responseRate: 70,
    packages: [
      {
        id: 1,
        packageType: "Light",
        trainingType: "in-person",
        recommended: false,
        title: "In-Person Training for up to 4 athletes",
        description: `3 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 105,
        sessionSalary: "3 sessions ($35/ea)",
      },
      {
        id: 2,
        packageType: "Standard",
        trainingType: "in-person",
        recommended: true,
        title: "In-Person Training for up to 10 athletes",
        description: `6 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 175,
        sessionSalary: "6 sessions ($35/ea)",
      },
      {
        id: 3,
        packageType: "Pro",
        trainingType: "online",
        recommended: false,
        title: "Online Training for a single athlete",
        description: `10 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 250,
        sessionSalary: "10 sessions ($35/ea)",
      },
    ],
    credentials: [
      {
        id: 4,
        college: ["x EssexxCounty", "Community College (NJ)"],
        experience: "30 years",
        accreditations: [
          "x EssexxCounty Qualified",
          "Private Coach",
          "Passed Coach Course",
        ],
      },
    ],
    services: [
      {
        ages: ["Kids", "Teenagers"],
        positions: [
          "Offensive Line",
          "Defensive Back",
          "Kicker",
          "Quarterback",
          "Running Back",
          "Tight End",
          "Wide Receiver",
          "Defensive Line",
          "Linebacker",
        ],
        specialties: [
          "Blocking",
          "Catching",
          "Jamming",
          "Kicking",
          "Special Teams",
          "Tackling",
          "Throwing",
          "Pass Defense",
          "Footwork",
          "Route Running",
          "Hand Placement",
        ],
      },
    ],
    actionPhotos: [
      actionPhoto1,
      actionPhoto2,
      actionPhoto3,
      actionPhoto4,
      actionPhoto5,
    ],
    experience:
      "I have played sports like baseball, football, basketball and boxing. I have played football from age 8 up to age 18, were I learned to play both side of the ball. I have played youth and semi pro football. I have been coaching football on two levels one as a semi pro and the other as a youth coach. I started coaching semi pro in 1994 up until 2007. and I started coaching youth football in 1996. at both levels I coach defense , I attend Glazer football Clinic an I'm USA coach certified. I still coach youth football now for the Linden Tigers. I also coach baseball for the linden PAL , which I have been doing for 3years now. Before than II coached in East Orange Little League two years, and Newark Little League for 3 years. I now have my own double A adult baseball team which has play in 3 se",
    highlights:
      "Won 5 championship and 6 division championship these are with both semi pro and youth football. I have some of my players go on to play in the NFL and a few other play arena football.l I have taught players skill and technique to help them develop in this sport they play.. I also know Baseball, basketball, and boxing as well.",
    plan: "First I will talk to my client to see where he/ she is having problem or need up. After that I will have him or her warm up than we will go through some drill. than we will work on the problem, Than we will put everything together.exploding out of your stand to receive the ball . Than we will work on the receiving the ball from the quarterback. Learn the holes and the different way offensive use them. You will learn how to come out of the back field, running your ro out of the back field.utes to catch a pass.",
  },
  {
    id: 4,
    name: "leo",
    category: "Fitness Coach",
    categories: ["Football", "Fitness", "Swimming", "Basketball"],
    rating: 4,
    reviews: 100,
    badge: "Gold",
    summary:
      "Professional trainer, experience with athletes ranging from pro to youth. As a former pro athlete, I understand what it takes to reach your fitness goals. Sports Science degree",
    location: "LA",
    distance: 5.5,
    verified: true,
    salary: 40,
    image: img5,
    recommended: true,
    trainingType: "In-Person",
    gender: "Female",
    responseRate: 60,
    packages: [
      {
        id: 1,
        packageType: "Light",
        trainingType: "in-person",
        recommended: false,
        title: "In-Person Training for up to 4 athletes",
        description: `3 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 105,
        sessionSalary: "3 sessions ($35/ea)",
      },
      {
        id: 2,
        packageType: "Standard",
        trainingType: "in-person",
        recommended: true,
        title: "In-Person Training for up to 10 athletes",
        description: `6 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 175,
        sessionSalary: "6 sessions ($35/ea)",
      },
      {
        id: 3,
        packageType: "Pro",
        trainingType: "online",
        recommended: false,
        title: "Online Training for a single athlete",
        description: `10 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 250,
        sessionSalary: "10 sessions ($35/ea)",
      },
    ],
    credentials: [
      {
        id: 5,
        college: ["x EssexxCounty", "Community College (NJ)"],
        experience: "30 years",
        accreditations: [
          "x EssexxCounty Qualified",
          "Private Coach",
          "Passed Coach Course",
        ],
      },
    ],
    services: [
      {
        ages: ["Kids", "Teenagers"],
        positions: [
          "Offensive Line",
          "Defensive Back",
          "Kicker",
          "Quarterback",
          "Running Back",
          "Tight End",
          "Wide Receiver",
          "Defensive Line",
          "Linebacker",
        ],
        specialties: [
          "Blocking",
          "Catching",
          "Jamming",
          "Kicking",
          "Special Teams",
          "Tackling",
          "Throwing",
          "Pass Defense",
          "Footwork",
          "Route Running",
          "Hand Placement",
        ],
      },
    ],
    actionPhotos: [
      actionPhoto1,
      actionPhoto2,
      actionPhoto3,
      actionPhoto4,
      actionPhoto5,
    ],
    experience:
      "I have played sports like baseball, football, basketball and boxing. I have played football from age 8 up to age 18, were I learned to play both side of the ball. I have played youth and semi pro football. I have been coaching football on two levels one as a semi pro and the other as a youth coach. I started coaching semi pro in 1994 up until 2007. and I started coaching youth football in 1996. at both levels I coach defense , I attend Glazer football Clinic an I'm USA coach certified. I still coach youth football now for the Linden Tigers. I also coach baseball for the linden PAL , which I have been doing for 3years now. Before than II coached in East Orange Little League two years, and Newark Little League for 3 years. I now have my own double A adult baseball team which has play in 3 se",
    highlights:
      "Won 5 championship and 6 division championship these are with both semi pro and youth football. I have some of my players go on to play in the NFL and a few other play arena football.l I have taught players skill and technique to help them develop in this sport they play.. I also know Baseball, basketball, and boxing as well.",
    plan: "First I will talk to my client to see where he/ she is having problem or need up. After that I will have him or her warm up than we will go through some drill. than we will work on the problem, Than we will put everything together.exploding out of your stand to receive the ball . Than we will work on the receiving the ball from the quarterback. Learn the holes and the different way offensive use them. You will learn how to come out of the back field, running your ro out of the back field.utes to catch a pass.",
  },
  {
    id: 5,
    name: "leo",
    category: "Fitness Coach",
    categories: ["Football", "Fitness", "Swimming", "Basketball"],
    rating: 4,
    reviews: 100,
    badge: "bronze",
    summary:
      "Professional trainer, experience with athletes ranging from pro to youth. As a former pro athlete, I understand what it takes to reach your fitness goals. Sports Science degree",
    location: "LA",
    distance: 5.5,
    verified: true,
    salary: 50,
    image: img6,
    recommended: true,
    trainingType: "Online",
    gender: "Male",
    responseRate: 40,
    packages: [
      {
        id: 1,
        packageType: "Light",
        trainingType: "in-person",
        recommended: false,
        title: "In-Person Training for up to 4 athletes",
        description: `3 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 105,
        sessionSalary: "3 sessions ($35/ea)",
      },
      {
        id: 2,
        packageType: "Standard",
        trainingType: "in-person",
        recommended: true,
        title: "In-Person Training for up to 10 athletes",
        description: `6 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 175,
        sessionSalary: "6 sessions ($35/ea)",
      },
      {
        id: 3,
        packageType: "Pro",
        trainingType: "online",
        recommended: false,
        title: "Online Training for a single athlete",
        description: `10 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 250,
        sessionSalary: "10 sessions ($35/ea)",
      },
    ],
    credentials: [
      {
        id: 6,
        college: ["x EssexxCounty", "Community College (NJ)"],
        experience: "30 years",
        accreditations: [
          "x EssexxCounty Qualified",
          "Private Coach",
          "Passed Coach Course",
        ],
      },
    ],
    services: [
      {
        ages: ["Kids", "Teenagers"],
        positions: [
          "Offensive Line",
          "Defensive Back",
          "Kicker",
          "Quarterback",
          "Running Back",
          "Tight End",
          "Wide Receiver",
          "Defensive Line",
          "Linebacker",
        ],
        specialties: [
          "Blocking",
          "Catching",
          "Jamming",
          "Kicking",
          "Special Teams",
          "Tackling",
          "Throwing",
          "Pass Defense",
          "Footwork",
          "Route Running",
          "Hand Placement",
        ],
      },
    ],
    actionPhotos: [
      actionPhoto1,
      actionPhoto2,
      actionPhoto3,
      actionPhoto4,
      actionPhoto5,
    ],
    experience:
      "I have played sports like baseball, football, basketball and boxing. I have played football from age 8 up to age 18, were I learned to play both side of the ball. I have played youth and semi pro football. I have been coaching football on two levels one as a semi pro and the other as a youth coach. I started coaching semi pro in 1994 up until 2007. and I started coaching youth football in 1996. at both levels I coach defense , I attend Glazer football Clinic an I'm USA coach certified. I still coach youth football now for the Linden Tigers. I also coach baseball for the linden PAL , which I have been doing for 3years now. Before than II coached in East Orange Little League two years, and Newark Little League for 3 years. I now have my own double A adult baseball team which has play in 3 se",
    highlights:
      "Won 5 championship and 6 division championship these are with both semi pro and youth football. I have some of my players go on to play in the NFL and a few other play arena football.l I have taught players skill and technique to help them develop in this sport they play.. I also know Baseball, basketball, and boxing as well.",
    plan: "First I will talk to my client to see where he/ she is having problem or need up. After that I will have him or her warm up than we will go through some drill. than we will work on the problem, Than we will put everything together.exploding out of your stand to receive the ball . Than we will work on the receiving the ball from the quarterback. Learn the holes and the different way offensive use them. You will learn how to come out of the back field, running your ro out of the back field.utes to catch a pass.",
  },
  {
    id: 6,
    name: "leo",
    category: "Fitness Coach",
    categories: ["Football", "Fitness", "Swimming", "Basketball"],
    rating: 4,
    reviews: 100,
    badge: "bronze",
    summary:
      "Professional trainer, experience with athletes ranging from pro to youth. As a former pro athlete, I understand what it takes to reach your fitness goals. Sports Science degree",
    location: "LA",
    distance: 5.5,
    salary: 50,
    image: img7,
    recommended: false,
    trainingType: "In-Person",
    gender: "Female",
    responseRate: 40,
    packages: [
      {
        id: 1,
        packageType: "Light",
        trainingType: "in-person",
        recommended: false,
        title: "In-Person Training for up to 4 athletes",
        description: `3 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 105,
        sessionSalary: "3 sessions ($35/ea)",
      },
      {
        id: 2,
        packageType: "Standard",
        trainingType: "in-person",
        recommended: true,
        title: "In-Person Training for up to 10 athletes",
        description: `6 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 175,
        sessionSalary: "6 sessions ($35/ea)",
      },
      {
        id: 3,
        packageType: "Pro",
        trainingType: "online",
        recommended: false,
        title: "Online Training for a single athlete",
        description: `10 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 250,
        sessionSalary: "10 sessions ($35/ea)",
      },
    ],
    credentials: [
      {
        id: 7,
        college: ["x EssexxCounty", "Community College (NJ)"],
        experience: "30 years",
        accreditations: [
          "x EssexxCounty Qualified",
          "Private Coach",
          "Passed Coach Course",
        ],
      },
    ],
    services: [
      {
        ages: ["Kids", "Teenagers"],
        positions: [
          "Offensive Line",
          "Defensive Back",
          "Kicker",
          "Quarterback",
          "Running Back",
          "Tight End",
          "Wide Receiver",
          "Defensive Line",
          "Linebacker",
        ],
        specialties: [
          "Blocking",
          "Catching",
          "Jamming",
          "Kicking",
          "Special Teams",
          "Tackling",
          "Throwing",
          "Pass Defense",
          "Footwork",
          "Route Running",
          "Hand Placement",
        ],
      },
    ],
    actionPhotos: [
      actionPhoto1,
      actionPhoto2,
      actionPhoto3,
      actionPhoto4,
      actionPhoto5,
    ],
    experience:
      "I have played sports like baseball, football, basketball and boxing. I have played football from age 8 up to age 18, were I learned to play both side of the ball. I have played youth and semi pro football. I have been coaching football on two levels one as a semi pro and the other as a youth coach. I started coaching semi pro in 1994 up until 2007. and I started coaching youth football in 1996. at both levels I coach defense , I attend Glazer football Clinic an I'm USA coach certified. I still coach youth football now for the Linden Tigers. I also coach baseball for the linden PAL , which I have been doing for 3years now. Before than II coached in East Orange Little League two years, and Newark Little League for 3 years. I now have my own double A adult baseball team which has play in 3 se",
    highlights:
      "Won 5 championship and 6 division championship these are with both semi pro and youth football. I have some of my players go on to play in the NFL and a few other play arena football.l I have taught players skill and technique to help them develop in this sport they play.. I also know Baseball, basketball, and boxing as well.",
    plan: "First I will talk to my client to see where he/ she is having problem or need up. After that I will have him or her warm up than we will go through some drill. than we will work on the problem, Than we will put everything together.exploding out of your stand to receive the ball . Than we will work on the receiving the ball from the quarterback. Learn the holes and the different way offensive use them. You will learn how to come out of the back field, running your ro out of the back field.utes to catch a pass.",
  },
  {
    id: 7,
    name: "leo",
    category: "Fitness Coach",
    categories: ["Football", "Fitness", "Swimming", "Basketball"],
    rating: 4,
    reviews: 100,
    badge: "gold",
    summary:
      "Professional trainer, experience with athletes ranging from pro to youth. As a former pro athlete, I understand what it takes to reach your fitness goals. Sports Science degree",
    location: "LA",
    distance: 5.5,
    salary: 50,
    image: img4,
    recommended: true,
    trainingType: "In-Person",
    gender: "Female",
    responseRate: 70,
    packages: [
      {
        id: 1,
        packageType: "Light",
        trainingType: "in-person",
        recommended: false,
        title: "In-Person Training for up to 4 athletes",
        description: `3 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 105,
        sessionSalary: "3 sessions ($35/ea)",
      },
      {
        id: 2,
        packageType: "Standard",
        trainingType: "in-person",
        recommended: true,
        title: "In-Person Training for up to 10 athletes",
        description: `6 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 175,
        sessionSalary: "6 sessions ($35/ea)",
      },
      {
        id: 3,
        packageType: "Pro",
        trainingType: "online",
        recommended: false,
        title: "Online Training for a single athlete",
        description: `10 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 250,
        sessionSalary: "10 sessions ($35/ea)",
      },
    ],
    credentials: [
      {
        id: 7,
        college: ["x EssexxCounty", "Community College (NJ)"],
        experience: "30 years",
        accreditations: [
          "x EssexxCounty Qualified",
          "Private Coach",
          "Passed Coach Course",
        ],
      },
    ],
    services: [
      {
        ages: ["Kids", "Teenagers"],
        positions: [
          "Offensive Line",
          "Defensive Back",
          "Kicker",
          "Quarterback",
          "Running Back",
          "Tight End",
          "Wide Receiver",
          "Defensive Line",
          "Linebacker",
        ],
        specialties: [
          "Blocking",
          "Catching",
          "Jamming",
          "Kicking",
          "Special Teams",
          "Tackling",
          "Throwing",
          "Pass Defense",
          "Footwork",
          "Route Running",
          "Hand Placement",
        ],
      },
    ],
    actionPhotos: [
      actionPhoto1,
      actionPhoto2,
      actionPhoto3,
      actionPhoto4,
      actionPhoto5,
    ],
    experience:
      "I have played sports like baseball, football, basketball and boxing. I have played football from age 8 up to age 18, were I learned to play both side of the ball. I have played youth and semi pro football. I have been coaching football on two levels one as a semi pro and the other as a youth coach. I started coaching semi pro in 1994 up until 2007. and I started coaching youth football in 1996. at both levels I coach defense , I attend Glazer football Clinic an I'm USA coach certified. I still coach youth football now for the Linden Tigers. I also coach baseball for the linden PAL , which I have been doing for 3years now. Before than II coached in East Orange Little League two years, and Newark Little League for 3 years. I now have my own double A adult baseball team which has play in 3 se",
    highlights:
      "Won 5 championship and 6 division championship these are with both semi pro and youth football. I have some of my players go on to play in the NFL and a few other play arena football.l I have taught players skill and technique to help them develop in this sport they play.. I also know Baseball, basketball, and boxing as well.",
    plan: "First I will talk to my client to see where he/ she is having problem or need up. After that I will have him or her warm up than we will go through some drill. than we will work on the problem, Than we will put everything together.exploding out of your stand to receive the ball . Than we will work on the receiving the ball from the quarterback. Learn the holes and the different way offensive use them. You will learn how to come out of the back field, running your ro out of the back field.utes to catch a pass.",
  },
  {
    id: 8,
    name: "leo",
    category: "Fitness Coach",
    categories: ["Football", "Fitness", "Swimming", "Basketball"],
    rating: 4,
    reviews: 100,
    badge: "selver",
    summary:
      "Professional trainer, experience with athletes ranging from pro to youth. As a former pro athlete, I understand what it takes to reach your fitness goals. Sports Science degree",
    location: "LA",
    distance: 5.5,
    salary: 50,
    image: img5,
    recommended: false,
    trainingType: "In-Person",
    gender: "Female",
    responseRate: 100,
    packages: [
      {
        id: 1,
        packageType: "Light",
        trainingType: "in-person",
        recommended: false,
        title: "In-Person Training for up to 4 athletes",
        description: `3 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 105,
        sessionSalary: "3 sessions ($35/ea)",
      },
      {
        id: 2,
        packageType: "Standard",
        trainingType: "in-person",
        recommended: true,
        title: "In-Person Training for up to 10 athletes",
        description: `6 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 175,
        sessionSalary: "6 sessions ($35/ea)",
      },
      {
        id: 3,
        packageType: "Pro",
        trainingType: "online",
        recommended: false,
        title: "Online Training for a single athlete",
        description: `10 session package with Coach John Doe. 60 minute session length`,
        sessionLength: "1 hour",
        salary: 250,
        sessionSalary: "10 sessions ($35/ea)",
      },
    ],
    credentials: [
      {
        id: 7,
        college: ["x EssexxCounty", "Community College (NJ)"],
        experience: "30 years",
        accreditations: [
          "x EssexxCounty Qualified",
          "Private Coach",
          "Passed Coach Course",
        ],
      },
    ],
    services: [
      {
        ages: ["Kids", "Teenagers"],
        positions: [
          "Offensive Line",
          "Defensive Back",
          "Kicker",
          "Quarterback",
          "Running Back",
          "Tight End",
          "Wide Receiver",
          "Defensive Line",
          "Linebacker",
        ],
        specialties: [
          "Blocking",
          "Catching",
          "Jamming",
          "Kicking",
          "Special Teams",
          "Tackling",
          "Throwing",
          "Pass Defense",
          "Footwork",
          "Route Running",
          "Hand Placement",
        ],
      },
    ],
    actionPhotos: [
      actionPhoto1,
      actionPhoto2,
      actionPhoto3,
      actionPhoto4,
      actionPhoto5,
    ],
    experience:
      "I have played sports like baseball, football, basketball and boxing. I have played football from age 8 up to age 18, were I learned to play both side of the ball. I have played youth and semi pro football. I have been coaching football on two levels one as a semi pro and the other as a youth coach. I started coaching semi pro in 1994 up until 2007. and I started coaching youth football in 1996. at both levels I coach defense , I attend Glazer football Clinic an I'm USA coach certified. I still coach youth football now for the Linden Tigers. I also coach baseball for the linden PAL , which I have been doing for 3years now. Before than II coached in East Orange Little League two years, and Newark Little League for 3 years. I now have my own double A adult baseball team which has play in 3 se",
    highlights:
      "Won 5 championship and 6 division championship these are with both semi pro and youth football. I have some of my players go on to play in the NFL and a few other play arena football.l I have taught players skill and technique to help them develop in this sport they play.. I also know Baseball, basketball, and boxing as well.",
    plan: "First I will talk to my client to see where he/ she is having problem or need up. After that I will have him or her warm up than we will go through some drill. than we will work on the problem, Than we will put everything together.exploding out of your stand to receive the ball . Than we will work on the receiving the ball from the quarterback. Learn the holes and the different way offensive use them. You will learn how to come out of the back field, running your ro out of the back field.utes to catch a pass.",
  },
];
