import IntroInfo from "../../components/IntroInfo/IntroInfo"
import styles from "./IntroPage.module.css"
const IntroPage = () => {
    return ( <>
    <IntroInfo/>
    <div className={styles.continer}>
        <p>
        Simply put, CoachUp coaching works. Every day, across the country, CoachUp athletes training with CoachUp coaches are learning new moves, polishing up their games, and building their confidence on the court or playing field. They are well on their way to the next level, and the one after that. And they feel great!
        </p>
        <p className="mt-5">But don’t take our word for it. Check out what actual parents and athletes using CoachUp are saying:</p>
      <span className={styles.line}></span>
      <p className="mt-4 mb-5">
      "In one word, I would describe private coaching as crucial. Although I was gifted athletically, to really bring my skills along I needed someone who would always be there with me, helping me. My coach was always there for me, and that’s something I really appreciate. It’s amazing having that one-on-one time and help on my game, and it’s something I really need now more than ever as a rookie. I definitely share CoachUp’s belief that private coaching can change kids’ lives."
        </p>
        <h4>Nerlens Noel, NBA basketball player, Sixth pick in the 2013 NBA draft</h4>
      <span className={styles.line}></span>
      <p>"I am very fond of the idea of CoachUp and enthusiastic about it. Anytime you can have extra training, guidance, and help in something that you enjoy doing, and in which you have shown the capacity and desire to improve, it’s a great thing. To have CoachUp as a resource to help you improve is huge. When I was playing as a point guard, my job was to assist and orchestrate. CoachUp is doing that in another form -- assisting young players in their journey to reach the next level. What could be better than that?"</p>
    <h4 className="mt-5">Tommy Amaker, Head Coach, Harvard University Men's Basketball</h4>
    <span className={styles.line}></span>
  <p>"There is no substitute for a great private coach — someone who can really teach you the intricacies of the game, and break down the fundamentals that make all the difference. The thing I love about CoachUp is that the coaches are vetted. That fact provides a level of security and takes some concern away. A lot of times, people choose coaches by word of mouth, which is a less reliable approach. The beauty of CoachUp is that the coaches are vetted not just for security issues, but for actually having the skill sets you’re looking for. For instance, maybe you’re a soccer player, and in the off-season you’re feeling kind of burned out in terms of playing the game. You can go to CoachUp and find yourself a personal trainer to just get you into better condition. But if you want to focus on footwork in particular, you can find a good trainer for footwork. It's a great resource for any athlete. I highly recommend CoachUp — it's an excellent choice for any athlete looking to take his or her game to the next level!"</p>
  <h4 className="mt-5">Cam Neely, President of the Boston Bruins, hockey legend, and sports dad</h4>
  <span className={styles.line}></span>
  <p>"I am very fond of the idea of CoachUp and enthusiastic about it. Anytime you can have extra training, guidance, and help in something that you enjoy doing, and in which you have shown the capacity and desire to improve, it’s a great thing. To have CoachUp as a resource to help you improve is huge. When I was playing as a point guard, my job was to assist and orchestrate. CoachUp is doing that in another form -- assisting young players in their journey to reach the next level. What could be better than that?"</p>
    <h4 className="mt-5">Tommy Amaker, Head Coach, Harvard University Men's Basketball</h4>
    <span className={styles.line}></span>
  <p>"There is no substitute for a great private coach — someone who can really teach you the intricacies of the game, and break down the fundamentals that make all the difference. The thing I love about CoachUp is that the coaches are vetted. That fact provides a level of security and takes some concern away. A lot of times, people choose coaches by word of mouth, which is a less reliable approach. The beauty of CoachUp is that the coaches are vetted not just for security issues, but for actually having the skill sets you’re looking for. For instance, maybe you’re a soccer player, and in the off-season you’re feeling kind of burned out in terms of playing the game. You can go to CoachUp and find yourself a personal trainer to just get you into better condition. But if you want to focus on footwork in particular, you can find a good trainer for footwork. It's a great resource for any athlete. I highly recommend CoachUp — it's an excellent choice for any athlete looking to take his or her game to the next level!"</p>
  <h4 className="mt-5">Cam Neely, President of the Boston Bruins, hockey legend, and sports dad</h4>
  <span className={styles.line}></span>
  <p>"I am very fond of the idea of CoachUp and enthusiastic about it. Anytime you can have extra training, guidance, and help in something that you enjoy doing, and in which you have shown the capacity and desire to improve, it’s a great thing. To have CoachUp as a resource to help you improve is huge. When I was playing as a point guard, my job was to assist and orchestrate. CoachUp is doing that in another form -- assisting young players in their journey to reach the next level. What could be better than that?"</p>
    <h4 className="mt-5">Tommy Amaker, Head Coach, Harvard University Men's Basketball</h4>
    <span className={styles.line}></span>
  <p>"There is no substitute for a great private coach — someone who can really teach you the intricacies of the game, and break down the fundamentals that make all the difference. The thing I love about CoachUp is that the coaches are vetted. That fact provides a level of security and takes some concern away. A lot of times, people choose coaches by word of mouth, which is a less reliable approach. The beauty of CoachUp is that the coaches are vetted not just for security issues, but for actually having the skill sets you’re looking for. For instance, maybe you’re a soccer player, and in the off-season you’re feeling kind of burned out in terms of playing the game. You can go to CoachUp and find yourself a personal trainer to just get you into better condition. But if you want to focus on footwork in particular, you can find a good trainer for footwork. It's a great resource for any athlete. I highly recommend CoachUp — it's an excellent choice for any athlete looking to take his or her game to the next level!"</p>
  <h4 className="mt-5">Cam Neely, President of the Boston Bruins, hockey legend, and sports dad</h4>
  <span className={styles.line}></span>
  <p>"I am very fond of the idea of CoachUp and enthusiastic about it. Anytime you can have extra training, guidance, and help in something that you enjoy doing, and in which you have shown the capacity and desire to improve, it’s a great thing. To have CoachUp as a resource to help you improve is huge. When I was playing as a point guard, my job was to assist and orchestrate. CoachUp is doing that in another form -- assisting young players in their journey to reach the next level. What could be better than that?"</p>
    <h4 className="mt-5">Tommy Amaker, Head Coach, Harvard University Men's Basketball</h4>
    <span className={styles.line}></span>
  <p>"There is no substitute for a great private coach — someone who can really teach you the intricacies of the game, and break down the fundamentals that make all the difference. The thing I love about CoachUp is that the coaches are vetted. That fact provides a level of security and takes some concern away. A lot of times, people choose coaches by word of mouth, which is a less reliable approach. The beauty of CoachUp is that the coaches are vetted not just for security issues, but for actually having the skill sets you’re looking for. For instance, maybe you’re a soccer player, and in the off-season you’re feeling kind of burned out in terms of playing the game. You can go to CoachUp and find yourself a personal trainer to just get you into better condition. But if you want to focus on footwork in particular, you can find a good trainer for footwork. It's a great resource for any athlete. I highly recommend CoachUp — it's an excellent choice for any athlete looking to take his or her game to the next level!"</p>
  <h4 className="mt-5">Cam Neely, President of the Boston Bruins, hockey legend, and sports dad</h4>
  <span className={styles.line}></span>
  <p>"I am very fond of the idea of CoachUp and enthusiastic about it. Anytime you can have extra training, guidance, and help in something that you enjoy doing, and in which you have shown the capacity and desire to improve, it’s a great thing. To have CoachUp as a resource to help you improve is huge. When I was playing as a point guard, my job was to assist and orchestrate. CoachUp is doing that in another form -- assisting young players in their journey to reach the next level. What could be better than that?"</p>
    <h4 className="mt-5">Tommy Amaker, Head Coach, Harvard University Men's Basketball</h4>
    <span className={styles.line}></span>
  <p>"There is no substitute for a great private coach — someone who can really teach you the intricacies of the game, and break down the fundamentals that make all the difference. The thing I love about CoachUp is that the coaches are vetted. That fact provides a level of security and takes some concern away. A lot of times, people choose coaches by word of mouth, which is a less reliable approach. The beauty of CoachUp is that the coaches are vetted not just for security issues, but for actually having the skill sets you’re looking for. For instance, maybe you’re a soccer player, and in the off-season you’re feeling kind of burned out in terms of playing the game. You can go to CoachUp and find yourself a personal trainer to just get you into better condition. But if you want to focus on footwork in particular, you can find a good trainer for footwork. It's a great resource for any athlete. I highly recommend CoachUp — it's an excellent choice for any athlete looking to take his or her game to the next level!"</p>
  <h4 className="mt-5">Cam Neely, President of the Boston Bruins, hockey legend, and sports dad</h4>
  <span className={styles.line}></span>
  <p>"I am very fond of the idea of CoachUp and enthusiastic about it. Anytime you can have extra training, guidance, and help in something that you enjoy doing, and in which you have shown the capacity and desire to improve, it’s a great thing. To have CoachUp as a resource to help you improve is huge. When I was playing as a point guard, my job was to assist and orchestrate. CoachUp is doing that in another form -- assisting young players in their journey to reach the next level. What could be better than that?"</p>
    <h4 className="mt-5">Tommy Amaker, Head Coach, Harvard University Men's Basketball</h4>
    <span className={styles.line}></span>
  <p>"There is no substitute for a great private coach — someone who can really teach you the intricacies of the game, and break down the fundamentals that make all the difference. The thing I love about CoachUp is that the coaches are vetted. That fact provides a level of security and takes some concern away. A lot of times, people choose coaches by word of mouth, which is a less reliable approach. The beauty of CoachUp is that the coaches are vetted not just for security issues, but for actually having the skill sets you’re looking for. For instance, maybe you’re a soccer player, and in the off-season you’re feeling kind of burned out in terms of playing the game. You can go to CoachUp and find yourself a personal trainer to just get you into better condition. But if you want to focus on footwork in particular, you can find a good trainer for footwork. It's a great resource for any athlete. I highly recommend CoachUp — it's an excellent choice for any athlete looking to take his or her game to the next level!"</p>
  <h4 className="mt-5">Cam Neely, President of the Boston Bruins, hockey legend, and sports dad</h4>
  <span className={styles.line}></span>

    </div>
    </> );
}
 
export default IntroPage;